### ISSUE TITLE
Translation: German

### ISSUE THREAD

**Issue by Mr-Kanister** [personalizedrefrigerator/joplin-plugin-freehand-drawing#1]
# Language name in English
German

# Translations
Please translate each of the strings in the right column (everything after the `: `) into the target language.

If you're updating an existing translation, please only include the strings you translated.

Ignore the surrounding single quotes. For example, to translate `insertDrawing: 'Insert Drawing',` to Spanish, please replace it with `insertDrawing: 'Añada dibujo',`.

	insertDrawing: 'Zeichnung einfügen',
	restoreFromAutosave: 'Automatische Sicherung wiederherstellen',
	deleteAutosave: 'Alle automatischen Sicherungen löschen',
	noSuchAutosaveExists: 'Keine automatischen Sicherungen vorhanden',
	discardChanges: 'Änderungen verwerfen',
	defaultImageTitle: 'Freihand-Zeichnen',

	edit: 'Bearbeiten',
	close: 'Schließen',
	save: 'Speichern',

	overwriteExisting: 'Existierende Zeichnung überschreiben',
	saveAsNewDrawing: 'Als neue Zeichnung speichern',
	clickOkToContinue: 'Fertig! Klicke auf „Ok“ um fortzufahen.',
	discardUnsavedChanges: 'Ungespeicherte Änderungen verwerfen?',
	resumeEditing: 'Bearbeiten fortfahren',

After translating the above strings, please also consider translating the strings in the editor. [These can be translated here.](https://github.com/personalizedrefrigerator/js-draw/issues/new?assignees=&labels=localization&template=translation.md&title=)

**Comment by personalizedrefrigerator** [comment]
Fixed by #2. Thank you for contributing!

**Comment by personalizedrefrigerator** [comment]
Thank you for your help! I'm preparing a new release.
![](https://user-images.githubusercontent.com/46334387/190882344-4722eb17-6125-4747-8769-344b4bd85ab2.png)
