### ISSUE TITLE
Cannot save

### ISSUE THREAD

**Issue by chenxiex** [personalizedrefrigerator/joplin-plugin-freehand-drawing#11]
![图片](https://github.com/personalizedrefrigerator/joplin-plugin-freehand-drawing/assets/28776935/c50e75a1-a9d3-4de7-816e-b7375bb1277b)
And the `/tmp/joplin-js-drawOvSkIF/tmp17.svg` doesn't exist.

**To Reproduce**

1. Write anything
2. Click on 'Save'
3. See error

**Expected behavior**
Images being saved

**Platform:**

- OS: Arch Linux
- Plugin Version: 2.7.1
- Joplin Version: 2.14.19

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!

After opening the drawing dialog and clicking "save", does the folder shown in the warning dialog exist? (Do any `/tmp/joplin-js-draw*` folders exist?).

**Comment by chenxiex** [comment]
after several reboot, I can no longer reproduce it.
