### ISSUE TITLE
Stylus buttons

### ISSUE THREAD

**Issue by Robin-Sch** [personalizedrefrigerator/joplin-plugin-freehand-drawing#13]
**Is your feature request related to a problem? Please describe.**
Whenever I want to erase something, I have to go up, press the "eraser" button and erase the thing. When I'm done, I have to go back and select the pen again.
On my stylus I have two buttons, and in other apps (like xournal++), I can configure these buttons to select the eraser tool whenever I press the button on it.

**Describe the solution you'd like**
A way to set stylus shortcuts for the eraser and other pen tools.

**Additional context**
When pressing the buttons right now it will draw, even when not pressing the drawing pad with my stylus.

**Comment by Robin-Sch** [comment]
https://github.com/personalizedrefrigerator/js-draw/issues/75
https://github.com/personalizedrefrigerator/js-draw/issues/52

**Comment by personalizedrefrigerator** [comment]
@Robin-Sch is this on Linux? If so (and if this is on Wayland), does running Joplin with Wayland support help? (Command line flags: `--enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland`).

**Comment by Robin-Sch** [comment]
Yes I am running wayland but when launching joplin under wayland instead of xwayland will not register any stylus events (except moving around). Touching the drawing pad with the stylus, the buttons on the stylus or the buttons on the drawing pad don't do anything (this is an issue across all wayland apps).

**Comment by personalizedrefrigerator** [comment]
Would adding a keybinding that acts like the eraser button help? Currently, pressing and releasing <kbd>4</kbd> activates the eraser, but releasing <kbd>4</kbd> doesn't switch back to the previous tool. If it would help, I could map <kbd>alt</kbd>-<kbd>e</kbd> (or something similar) to "enable eraser while pressed".

**Comment by Robin-Sch** [comment]
I mean.. If the keybindings would be customisable to use the stylus as binding that could work I guess

**Comment by personalizedrefrigerator** [comment]
> I mean.. If the keybindings would be customisable to use the stylus as binding that could work I guess

Based on a quick web search, it looks like it's possible, but rather difficult ([AskUbuntu: Mapping stylus buttons to different keys](https://askubuntu.com/questions/1224491/remap-btn-stylus-event-to-standard-keyboard-key)). Based on [this Chromium bug](https://issues.chromium.org/issues/40912660), I don't think it would be possible to remap the keybindings to stylus events from within Joplin.
