### ISSUE TITLE
How to delete a drawing from storage?

### ISSUE THREAD

**Issue by denilsonsa** [personalizedrefrigerator/joplin-plugin-freehand-drawing#14]
This is my first time using this plugin. I can easily create a drawing without any problem. In the markdown editor, it is inserted as a link to an SVG image. If I synchronize Jotlin with a local folder, I can see the new file in there, containing the SVG drawing I just created.

However, how do I delete it?

Sure, I can delete it from the note… But the drawing remains in the Jotlin storage.

---

After a while, I found out about *Tools→Note attachments…*, which shows the SVG image in there. However, there are so many items in that screen that it is impossible to know which drawings are orphan.

Can this plugin automatically purge its own drawings after they become unlinked from any note? If it cannot do that, consider it a feature request!

**Comment by personalizedrefrigerator** [comment]
Thank you for the feature request!

At present, Joplin [(should) automatically purge drawings](https://discourse.joplinapp.org/t/do-attachments-pictures-unattached-to-any-note-get-deleted-if-note-history-is-disabled/35308/3?u=personalizedrefriger) and other attachments after they have been deleted. The time this takes is determined by the "Keep note history for" setting, even if note history is disabled ([see this forum post](https://discourse.joplinapp.org/t/do-attachments-pictures-unattached-to-any-note-get-deleted-if-note-history-is-disabled/35308/3?u=personalizedrefriger)).

If this doesn't work, I can try to post instructions for manually deleting SVG drawings.

**Comment by denilsonsa** [comment]
Oh, I didn't know that! I read the whole README for this project, including the FAQ, and I saw a couple of questions about editing a drawing, but no question about deleting it.

Could you please add this (very valuable) information to the FAQ?
