### ISSUE TITLE
The new plugin does not support the old version of Joplin

### ISSUE THREAD

**Issue by sim0nwan9** [personalizedrefrigerator/joplin-plugin-freehand-drawing#16]
Hello, my joplin software version is 2.11.11, when I intalled 2.10.2 of freehand drawing plugin, it prompted me to upgrade Joplin software. But I don't want upgrade Joplin software as My computer is win7 system.  Can you give me old version freehand drawing(jpl file) ? I can not generate jpl from the code you pubilished.

**Comment by personalizedrefrigerator** [comment]
I've built a copy of the plugin from [this branch](https://github.com/personalizedrefrigerator/joplin-plugin-freehand-drawing/tree/test/support-older-joplin), which disables the features that require newer Joplin versions. I'm attaching the built plugin below:

 [io.github.personalizedrefrigerator.js-draw.jpl.zip](https://github.com/user-attachments/files/17852635/io.github.personalizedrefrigerator.js-draw.jpl.zip)

**Comment by personalizedrefrigerator** [comment]
I'm closing this as resolved. Please let me know if something else needs to be done.
