### ISSUE TITLE
Making editor/canvas area larger

### ISSUE THREAD

**Issue by mo-st** [personalizedrefrigerator/joplin-plugin-freehand-drawing#6]
First of all: thank you for this project, it makes Joplin so much more convenient!

**Is your feature request related to a problem? Please describe.**
I think the actual drawing area is relatively small, when zoomed to fill the maximum editor area while still keeping the entire canvas visible, only about a 1/4th of the total area of the whole joplin window. For taking notes in class this can be frustrating as right now I have to scroll up and down a bunch to see everything I have written. I also need to zoom in quite a lot because else the canvas is too small and I have to start new ones to often, which can be disruptive for concentration and workflow. Personally, I work with a wacom tablet and it is hard for me to draw accurately if the work area is too small relative to the total available screen space.
<img width="1477" alt="Screenshot 2023-04-25 at 21 50 06" src="https://user-images.githubusercontent.com/95215142/234388724-137ec7f9-dc98-4ff1-ba02-ef68d4c8a5e2.png">
This is what it looks like at a zoom level so the whole canvas is visible, normally I zoom in further to get a bit more real estate.

**Describe the solution you'd like**
Would it be possible to make the editor overlay the same size as the whole joplin window or even give a full screen option? This would allow me to take written notes or lecture drawings more intuitively because I have a larger area to work with and don't have to move the canvas around as often.

**Describe alternatives you've considered**
Right now I just zoom into the canvas more and move it around, while also enlarging joplin as much as possible. This is not ideal for the reasons mentioned above but also has the downside that line thickness is not consistent as this depends on the level of zoom. I think it would be better if the canvas would fill the whole window/screen so zooming isn't necessary.

Again, thank you for your work and for your consideration of this request.

**Comment by personalizedrefrigerator** [comment]
Hi!

Thank you for reporting this!

There's currently two regions you might be referring to:

**Region 1:**
![image](https://user-images.githubusercontent.com/46334387/234404175-8298e322-350a-456d-b15c-0d6123301217.png)

**Region 2:**
![image](https://user-images.githubusercontent.com/46334387/234404349-e6190044-4fc9-4deb-92ca-e1c89b4d845f.png)

## To change the size of region 2
The second region's size can be changed using the width/height options under the "page" menu:
![Page > width](https://user-images.githubusercontent.com/46334387/234404626-cc029bf3-2c4c-4e45-bde3-4844bbc0cf61.png)


## To change the size of region 1
This seems possible with `userstyles.css`. Thus, I should be able to fix this using the Joplin plugin API.

Should this be a setting that users can change or something that's always enabled?

**Comment by mo-st** [comment]
Thanks for the quick reply! Although I was referring to region 1, I was not aware of the feature to change the size of region 2. Thank you for pointing this out to me, this is also very useful to know.

As for the size of region 1: I think letting the user decide would be nice, I imagine different people use your tool for different purposes and not everyone might like a larger area. For me, taking the full area by default would be perfect.
But in the end, this is your decision and I am no expert on these things, I am happy you listened and reacted so quickly either way:)

**Comment by personalizedrefrigerator** [comment]
I've published an update! The editor should now be in fullscreen by default!

**Comment by mo-st** [comment]
I just tried it out and I love it! Thank you so much, this solved my issue perfectly. Have a lovely week dear personalizedrefrigerator.
