### ISSUE TITLE
Include .exe in realeses

### ISSUE THREAD

**Issue by BruhBruhDev** [personalizedrefrigerator/joplin-plugin-freehand-drawing#7]
It would be more user-friendly if there would be an already compiled file ready. As I would like to test it, even if it is in beta, but I don't want to waste time on learning how to compile it for a one time use.
Thank you for reading and considering it
Kind regards

**Comment by personalizedrefrigerator** [comment]
There's no need to download a .exe file — this plugin is available through Joplin's plugin repository.

[See the download instructions](https://joplin.github.io/website-plugin-discovery/downloadPlugin.html?id=io.github.personalizedrefrigerator.js-draw) on the plugin website.

**Comment by BruhBruhDev** [comment]
Thank you for the quick reply. Sorry my bad. Maybe add the words "download" or "get from" ...  by the links 😅

**Comment by personalizedrefrigerator** [comment]
Done! See 93df939b5b4882da459a94ed3191089780fac6b0
